// src/components/BlogPostCreateForm.vue
<template>
  <form @submit.prevent="submitForm">
    <h2>Add a blog post</h2>
    <div>
      <label>Title: <input name="title" required v-model="title" /></label>
      <span v-if="titleNotUnique" class="text-red">Title not unique</span>
    </div>
    <div>
      <label>Text: <input name="text" required /> </label>
    </div>
    <div>
      <label>Image: <input name="image" /> </label>
    </div>
    <div>
      <label>URL: <input name="url" /> </label>
    </div>
    <button type="submit" :disabled="titleNotUnique">Add post</button>
  </form>
</template>

<script>
import { computed, ref } from "@vue/reactivity";
export default {
  name: "BlogPostCreateForm",
  props: { posts: Array, addPost: Function },
  setup(props) {
    const title = ref("");
    return {
      title,
      titleNotUnique: computed(() =>
        props.posts.some(
          (p) =>
            p.title.trim().toLowerCase() == title.value.trim().toLowerCase()
        )
      ),
      submitForm({ target }) {
        const { title, text, image, url } = target.elements;
        props.addPost(title.value, text.value, image.value, url.value);
        target.reset();
        title.value = "";
      },
    };
  },
};
</script>

<style>
body {
  font-family: sans-serif;
}
.text-red {
  color: red;
}
</style>

// src/components/BlogPostCreateForm.react.jsx
import { useState, useMemo } from "react";

export default function BlogPostCreateForm({ posts, addPost }) {
  const [title, setTitle] = useState("");
  const [text, setText] = useState("");
  const [image, setImage] = useState("");
  const [url, setUrl] = useState("");

  function submitForm(e) {
    e.preventDefault();
    addPost(title, text, image, url);
    setTitle("");
    setText("");
    setImage("");
    setUrl("");
  }

  const titleNotUnique = useMemo(
    () =>
      posts.some(
        (p) => p.title.trim().toLowerCase() == title.trim().toLowerCase()
      ),
    [posts, title]
  );

  return (
    <form onSubmit={submitForm}>
      <h2>Add a blog post</h2>
      <div>
        <label>
          Title:
          <input
            value={title}
            onChange={(e) => setTitle(e.target.value)}
            required
          />
        </label>
        {titleNotUnique && <span className="text-red">Title not unique</span>}
      </div>
      <div>
        <label>
          Text:
          <input
            value={text}
            onChange={(e) => setText(e.target.value)}
            required
          />
        </label>
      </div>
      <div>
        <label>
          Image:
          <input value={image} onChange={(e) => setImage(e.target.value)} />
        </label>
      </div>
      <div>
        <label>
          URL:
          <input value={url} onChange={(e) => setUrl(e.target.value)} />
        </label>
      </div>
      <button type="submit" disabled={titleNotUnique}>
        Add post
      </button>
    </form>
  );
}
